
package br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Cadastro", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", wsdlLocation = "http://srv-sinacor01:25101/Sinacor/InformacaoApoio/InformacaoApoio.Integration.IEFinanceira.svc?singleWSDL")
public class Cadastro
    extends Service
{

    private final static URL CADASTRO_WSDL_LOCATION;
    private final static WebServiceException CADASTRO_EXCEPTION;
    private final static QName CADASTRO_QNAME = new QName("http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", "Cadastro");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://srv-sinacor01:25101/Sinacor/InformacaoApoio/InformacaoApoio.Integration.IEFinanceira.svc?singleWSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CADASTRO_WSDL_LOCATION = url;
        CADASTRO_EXCEPTION = e;
    }

    public Cadastro() {
        super(__getWsdlLocation(), CADASTRO_QNAME);
    }

    public Cadastro(WebServiceFeature... features) {
        super(__getWsdlLocation(), CADASTRO_QNAME, features);
    }

    public Cadastro(URL wsdlLocation) {
        super(wsdlLocation, CADASTRO_QNAME);
    }

    public Cadastro(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CADASTRO_QNAME, features);
    }

    public Cadastro(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Cadastro(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEFinanceira
     */
    @WebEndpoint(name = "CustomBinding_IEFinanceira")
    public IEFinanceira getCustomBindingIEFinanceira() {
        return super.getPort(new QName("http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", "CustomBinding_IEFinanceira"), IEFinanceira.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEFinanceira
     */
    @WebEndpoint(name = "CustomBinding_IEFinanceira")
    public IEFinanceira getCustomBindingIEFinanceira(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", "CustomBinding_IEFinanceira"), IEFinanceira.class, features);
    }

    /**
     * 
     * @return
     *     returns IEFinanceira
     */
    @WebEndpoint(name = "NetTcpBinding_IEFinanceira")
    public IEFinanceira getNetTcpBindingIEFinanceira() {
        return super.getPort(new QName("http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", "NetTcpBinding_IEFinanceira"), IEFinanceira.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEFinanceira
     */
    @WebEndpoint(name = "NetTcpBinding_IEFinanceira")
    public IEFinanceira getNetTcpBindingIEFinanceira(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", "NetTcpBinding_IEFinanceira"), IEFinanceira.class, features);
    }

    /**
     * 
     * @return
     *     returns IEFinanceira
     */
    @WebEndpoint(name = "NetTcpBinding_IEFinanceira1")
    public IEFinanceira getNetTcpBindingIEFinanceira1() {
        return super.getPort(new QName("http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", "NetTcpBinding_IEFinanceira1"), IEFinanceira.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEFinanceira
     */
    @WebEndpoint(name = "NetTcpBinding_IEFinanceira1")
    public IEFinanceira getNetTcpBindingIEFinanceira1(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", "NetTcpBinding_IEFinanceira1"), IEFinanceira.class, features);
    }

    /**
     * 
     * @return
     *     returns IEFinanceira
     */
    @WebEndpoint(name = "WSHttpBinding_IEFinanceira")
    public IEFinanceira getWSHttpBindingIEFinanceira() {
        return super.getPort(new QName("http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", "WSHttpBinding_IEFinanceira"), IEFinanceira.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEFinanceira
     */
    @WebEndpoint(name = "WSHttpBinding_IEFinanceira")
    public IEFinanceira getWSHttpBindingIEFinanceira(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", "WSHttpBinding_IEFinanceira"), IEFinanceira.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CADASTRO_EXCEPTION!= null) {
            throw CADASTRO_EXCEPTION;
        }
        return CADASTRO_WSDL_LOCATION;
    }

}
