
package br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira_integrationentity.CadastroInfoResponse;
import br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira_integrationentity.MovimentoResponse;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringDeclaradoia3Ss9NZ;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEFinanceira", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ObjectFactory.class,
    br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira_integrationentity.ObjectFactory.class,
    br.com.bovespa.sinacor_infra_service_security.ObjectFactory.class,
    br.com.sinacor.sinacor_infra_common_exceptions.ObjectFactory.class,
    br.com.sinacor.sinacor_infra_common_validation._2008._08.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class
})
public interface IEFinanceira {


    /**
     * 
     * @param password
     * @param companyId
     * @param username
     * @return
     *     returns java.lang.Boolean
     * @throws IEFinanceiraAuthenticateLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticateInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticateAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticateValidationFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticateGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticateBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Authenticate", action = "Authenticate")
    @WebResult(name = "AuthenticateResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.AuthenticateResponse")
    public Boolean authenticate(
        @WebParam(name = "username", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String username,
        @WebParam(name = "password", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String password,
        @WebParam(name = "companyId", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        Integer companyId)
        throws IEFinanceiraAuthenticateAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraAuthenticateBusinessFaultFaultFaultMessage, IEFinanceiraAuthenticateGeneralFaultFaultFaultMessage, IEFinanceiraAuthenticateInvalidSessionFaultFaultFaultMessage, IEFinanceiraAuthenticateLicensingFaultFaultFaultMessage, IEFinanceiraAuthenticateValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.Boolean
     * @throws IEFinanceiraAuthenticate2GeneralFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate2InvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate2AccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate2BusinessFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate2ValidationFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate2LicensingFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Authenticate2", action = "Authenticate2")
    @WebResult(name = "Authenticate2Result", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
    @RequestWrapper(localName = "Authenticate2", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate2")
    @ResponseWrapper(localName = "Authenticate2Response", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate2Response")
    public Boolean authenticate2(
        @WebParam(name = "username", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String username,
        @WebParam(name = "password", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String password)
        throws IEFinanceiraAuthenticate2AccessIsDeniedFaultFaultFaultMessage, IEFinanceiraAuthenticate2BusinessFaultFaultFaultMessage, IEFinanceiraAuthenticate2GeneralFaultFaultFaultMessage, IEFinanceiraAuthenticate2InvalidSessionFaultFaultFaultMessage, IEFinanceiraAuthenticate2LicensingFaultFaultFaultMessage, IEFinanceiraAuthenticate2ValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param companyId
     * @param domain
     * @param username
     * @param encryptedPassword
     * @return
     *     returns java.lang.Boolean
     * @throws IEFinanceiraAuthenticate3InvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate3AccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate3ValidationFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate3LicensingFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate3GeneralFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate3BusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Authenticate3", action = "Authenticate3")
    @WebResult(name = "Authenticate3Result", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
    @RequestWrapper(localName = "Authenticate3", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate3")
    @ResponseWrapper(localName = "Authenticate3Response", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate3Response")
    public Boolean authenticate3(
        @WebParam(name = "domain", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String domain,
        @WebParam(name = "username", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String username,
        @WebParam(name = "encryptedPassword", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String encryptedPassword,
        @WebParam(name = "companyId", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        Integer companyId)
        throws IEFinanceiraAuthenticate3AccessIsDeniedFaultFaultFaultMessage, IEFinanceiraAuthenticate3BusinessFaultFaultFaultMessage, IEFinanceiraAuthenticate3GeneralFaultFaultFaultMessage, IEFinanceiraAuthenticate3InvalidSessionFaultFaultFaultMessage, IEFinanceiraAuthenticate3LicensingFaultFaultFaultMessage, IEFinanceiraAuthenticate3ValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param domain
     * @param username
     * @param encryptedPassword
     * @return
     *     returns java.lang.Boolean
     * @throws IEFinanceiraAuthenticate4AccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate4InvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate4BusinessFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate4LicensingFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate4GeneralFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate4ValidationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Authenticate4", action = "Authenticate4")
    @WebResult(name = "Authenticate4Result", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
    @RequestWrapper(localName = "Authenticate4", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate4")
    @ResponseWrapper(localName = "Authenticate4Response", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate4Response")
    public Boolean authenticate4(
        @WebParam(name = "domain", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String domain,
        @WebParam(name = "username", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String username,
        @WebParam(name = "encryptedPassword", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String encryptedPassword)
        throws IEFinanceiraAuthenticate4AccessIsDeniedFaultFaultFaultMessage, IEFinanceiraAuthenticate4BusinessFaultFaultFaultMessage, IEFinanceiraAuthenticate4GeneralFaultFaultFaultMessage, IEFinanceiraAuthenticate4InvalidSessionFaultFaultFaultMessage, IEFinanceiraAuthenticate4LicensingFaultFaultFaultMessage, IEFinanceiraAuthenticate4ValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param companyId
     * @param domain
     * @param plainTextPassword
     * @param username
     * @return
     *     returns java.lang.Boolean
     * @throws IEFinanceiraAuthenticate5InvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate5GeneralFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate5AccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate5LicensingFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate5BusinessFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate5ValidationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Authenticate5", action = "Authenticate5")
    @WebResult(name = "Authenticate5Result", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
    @RequestWrapper(localName = "Authenticate5", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate5")
    @ResponseWrapper(localName = "Authenticate5Response", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate5Response")
    public Boolean authenticate5(
        @WebParam(name = "domain", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String domain,
        @WebParam(name = "username", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String username,
        @WebParam(name = "plainTextPassword", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String plainTextPassword,
        @WebParam(name = "companyId", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        Integer companyId)
        throws IEFinanceiraAuthenticate5AccessIsDeniedFaultFaultFaultMessage, IEFinanceiraAuthenticate5BusinessFaultFaultFaultMessage, IEFinanceiraAuthenticate5GeneralFaultFaultFaultMessage, IEFinanceiraAuthenticate5InvalidSessionFaultFaultFaultMessage, IEFinanceiraAuthenticate5LicensingFaultFaultFaultMessage, IEFinanceiraAuthenticate5ValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param domain
     * @param plainTextPassword
     * @param username
     * @return
     *     returns java.lang.Boolean
     * @throws IEFinanceiraAuthenticate6GeneralFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate6ValidationFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate6InvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate6BusinessFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate6LicensingFaultFaultFaultMessage
     * @throws IEFinanceiraAuthenticate6AccessIsDeniedFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Authenticate6", action = "Authenticate6")
    @WebResult(name = "Authenticate6Result", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
    @RequestWrapper(localName = "Authenticate6", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate6")
    @ResponseWrapper(localName = "Authenticate6Response", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services", className = "br.com.bovespa.sinacor_infra_service_security.Authenticate6Response")
    public Boolean authenticate6(
        @WebParam(name = "domain", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String domain,
        @WebParam(name = "username", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String username,
        @WebParam(name = "plainTextPassword", targetNamespace = "http://www.bovespa.com.br/Sinacor.Infra.Service.Security.Services")
        String plainTextPassword)
        throws IEFinanceiraAuthenticate6AccessIsDeniedFaultFaultFaultMessage, IEFinanceiraAuthenticate6BusinessFaultFaultFaultMessage, IEFinanceiraAuthenticate6GeneralFaultFaultFaultMessage, IEFinanceiraAuthenticate6InvalidSessionFaultFaultFaultMessage, IEFinanceiraAuthenticate6LicensingFaultFaultFaultMessage, IEFinanceiraAuthenticate6ValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira_integrationentity.CadastroInfoResponse
     * @throws IEFinanceiraConsultaCadastroBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaCadastroLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaCadastroAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaCadastroGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaCadastroInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaCadastroValidationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaCadastro", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaCadastro")
    @WebResult(name = "ConsultaCadastroResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaCadastro", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaCadastro")
    @ResponseWrapper(localName = "ConsultaCadastroResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaCadastroResponse")
    public CadastroInfoResponse consultaCadastro(
        @WebParam(name = "request", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        CadastroInfoRequest request)
        throws IEFinanceiraConsultaCadastroAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaCadastroBusinessFaultFaultFaultMessage, IEFinanceiraConsultaCadastroGeneralFaultFaultFaultMessage, IEFinanceiraConsultaCadastroInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaCadastroLicensingFaultFaultFaultMessage, IEFinanceiraConsultaCadastroValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira_integrationentity.MovimentoResponse
     * @throws IEFinanceiraConsultaMovCCInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCCAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCCGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCCLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCCBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCCValidationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaMovCC", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaMovCC")
    @WebResult(name = "ConsultaMovCCResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaMovCC", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaMovCC")
    @ResponseWrapper(localName = "ConsultaMovCCResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaMovCCResponse")
    public MovimentoResponse consultaMovCC(
        @WebParam(name = "request", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        CadastroInfoRequest request)
        throws IEFinanceiraConsultaMovCCAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaMovCCBusinessFaultFaultFaultMessage, IEFinanceiraConsultaMovCCGeneralFaultFaultFaultMessage, IEFinanceiraConsultaMovCCInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaMovCCLicensingFaultFaultFaultMessage, IEFinanceiraConsultaMovCCValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira_integrationentity.MovimentoResponse
     * @throws IEFinanceiraConsultaMovCustodiaValidationFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCustodiaBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCustodiaInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCustodiaGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCustodiaLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovCustodiaAccessIsDeniedFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaMovCustodia", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaMovCustodia")
    @WebResult(name = "ConsultaMovCustodiaResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaMovCustodia", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaMovCustodia")
    @ResponseWrapper(localName = "ConsultaMovCustodiaResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaMovCustodiaResponse")
    public MovimentoResponse consultaMovCustodia(
        @WebParam(name = "request", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        CadastroInfoRequest request)
        throws IEFinanceiraConsultaMovCustodiaAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaMovCustodiaBusinessFaultFaultFaultMessage, IEFinanceiraConsultaMovCustodiaGeneralFaultFaultFaultMessage, IEFinanceiraConsultaMovCustodiaInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaMovCustodiaLicensingFaultFaultFaultMessage, IEFinanceiraConsultaMovCustodiaValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira_integrationentity.MovimentoResponse
     * @throws IEFinanceiraConsultaMovBovespaLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBovespaAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBovespaBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBovespaValidationFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBovespaInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBovespaGeneralFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaMovBovespa", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaMovBovespa")
    @WebResult(name = "ConsultaMovBovespaResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaMovBovespa", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaMovBovespa")
    @ResponseWrapper(localName = "ConsultaMovBovespaResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaMovBovespaResponse")
    public MovimentoResponse consultaMovBovespa(
        @WebParam(name = "request", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        CadastroInfoRequest request)
        throws IEFinanceiraConsultaMovBovespaAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaMovBovespaBusinessFaultFaultFaultMessage, IEFinanceiraConsultaMovBovespaGeneralFaultFaultFaultMessage, IEFinanceiraConsultaMovBovespaInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaMovBovespaLicensingFaultFaultFaultMessage, IEFinanceiraConsultaMovBovespaValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira_integrationentity.MovimentoResponse
     * @throws IEFinanceiraConsultaMovBMFAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBMFLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBMFGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBMFInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBMFValidationFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaMovBMFBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaMovBMF", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaMovBMF")
    @WebResult(name = "ConsultaMovBMFResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaMovBMF", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaMovBMF")
    @ResponseWrapper(localName = "ConsultaMovBMFResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaMovBMFResponse")
    public MovimentoResponse consultaMovBMF(
        @WebParam(name = "request", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        CadastroInfoRequest request)
        throws IEFinanceiraConsultaMovBMFAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaMovBMFBusinessFaultFaultFaultMessage, IEFinanceiraConsultaMovBMFGeneralFaultFaultFaultMessage, IEFinanceiraConsultaMovBMFInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaMovBMFLicensingFaultFaultFaultMessage, IEFinanceiraConsultaMovBMFValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param codigoEmpresa
     * @return
     *     returns br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.Declarante
     * @throws IEFinanceiraConsultaDeclaranteGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaranteAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaranteBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaranteLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaranteInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaranteValidationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaDeclarante", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaDeclarante")
    @WebResult(name = "ConsultaDeclaranteResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaDeclarante", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclarante")
    @ResponseWrapper(localName = "ConsultaDeclaranteResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaranteResponse")
    public Declarante consultaDeclarante(
        @WebParam(name = "codigoEmpresa", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        Integer codigoEmpresa)
        throws IEFinanceiraConsultaDeclaranteAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaDeclaranteBusinessFaultFaultFaultMessage, IEFinanceiraConsultaDeclaranteGeneralFaultFaultFaultMessage, IEFinanceiraConsultaDeclaranteInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaDeclaranteLicensingFaultFaultFaultMessage, IEFinanceiraConsultaDeclaranteValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringDeclaradoia3Ss9NZ
     * @throws IEFinanceiraConsultaDeclaradoBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradoAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradoLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradoGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradoValidationFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradoInvalidSessionFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaDeclarado", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaDeclarado")
    @WebResult(name = "ConsultaDeclaradoResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaDeclarado", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclarado")
    @ResponseWrapper(localName = "ConsultaDeclaradoResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradoResponse")
    public ArrayOfKeyValueOfstringDeclaradoia3Ss9NZ consultaDeclarado(
        @WebParam(name = "request", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        CadastroInfoRequest request)
        throws IEFinanceiraConsultaDeclaradoAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradoBusinessFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradoGeneralFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradoInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradoLicensingFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradoValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param companyId
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     * @throws IEFinanceiraConsultaDeclaradosCFCCBOVBMFLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCFCCBOVBMFBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCFCCBOVBMFInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCFCCBOVBMFAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCFCCBOVBMFValidationFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCFCCBOVBMFGeneralFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaDeclarados_CF_CC_BOV_BMF", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaDeclarados_CF_CC_BOV_BMF")
    @WebResult(name = "ConsultaDeclarados_CF_CC_BOV_BMFResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaDeclarados_CF_CC_BOV_BMF", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosCFCCBOVBMF")
    @ResponseWrapper(localName = "ConsultaDeclarados_CF_CC_BOV_BMFResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosCFCCBOVBMFResponse")
    public ArrayOfstring consultaDeclaradosCFCCBOVBMF(
        @WebParam(name = "companyId", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        Integer companyId)
        throws IEFinanceiraConsultaDeclaradosCFCCBOVBMFAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCFCCBOVBMFBusinessFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCFCCBOVBMFGeneralFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCFCCBOVBMFInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCFCCBOVBMFLicensingFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCFCCBOVBMFValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param companyId
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     * @throws IEFinanceiraConsultaDeclaradosCustodiaGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCustodiaInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCustodiaBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCustodiaLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCustodiaAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosCustodiaValidationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaDeclaradosCustodia", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaDeclaradosCustodia")
    @WebResult(name = "ConsultaDeclaradosCustodiaResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaDeclaradosCustodia", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosCustodia")
    @ResponseWrapper(localName = "ConsultaDeclaradosCustodiaResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosCustodiaResponse")
    public ArrayOfstring consultaDeclaradosCustodia(
        @WebParam(name = "companyId", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        Integer companyId)
        throws IEFinanceiraConsultaDeclaradosCustodiaAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCustodiaBusinessFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCustodiaGeneralFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCustodiaInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCustodiaLicensingFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosCustodiaValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param companyId
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     * @throws IEFinanceiraConsultaDeclaradosContaCorrenteBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosContaCorrenteInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosContaCorrenteAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosContaCorrenteValidationFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosContaCorrenteGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosContaCorrenteLicensingFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaDeclaradosContaCorrente", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaDeclaradosContaCorrente")
    @WebResult(name = "ConsultaDeclaradosContaCorrenteResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaDeclaradosContaCorrente", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosContaCorrente")
    @ResponseWrapper(localName = "ConsultaDeclaradosContaCorrenteResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosContaCorrenteResponse")
    public ArrayOfstring consultaDeclaradosContaCorrente(
        @WebParam(name = "companyId", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        Integer companyId)
        throws IEFinanceiraConsultaDeclaradosContaCorrenteAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosContaCorrenteBusinessFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosContaCorrenteGeneralFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosContaCorrenteInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosContaCorrenteLicensingFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosContaCorrenteValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param companyId
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     * @throws IEFinanceiraConsultaDeclaradosBovespaAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBovespaBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBovespaGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBovespaLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBovespaValidationFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBovespaInvalidSessionFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaDeclaradosBovespa", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaDeclaradosBovespa")
    @WebResult(name = "ConsultaDeclaradosBovespaResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaDeclaradosBovespa", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosBovespa")
    @ResponseWrapper(localName = "ConsultaDeclaradosBovespaResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosBovespaResponse")
    public ArrayOfstring consultaDeclaradosBovespa(
        @WebParam(name = "companyId", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        Integer companyId)
        throws IEFinanceiraConsultaDeclaradosBovespaAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBovespaBusinessFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBovespaGeneralFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBovespaInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBovespaLicensingFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBovespaValidationFaultFaultFaultMessage
    ;

    /**
     * 
     * @param companyId
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     * @throws IEFinanceiraConsultaDeclaradosBmfAccessIsDeniedFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBmfGeneralFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBmfLicensingFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBmfBusinessFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBmfInvalidSessionFaultFaultFaultMessage
     * @throws IEFinanceiraConsultaDeclaradosBmfValidationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultaDeclaradosBmf", action = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService/IEFinanceira/ConsultaDeclaradosBmf")
    @WebResult(name = "ConsultaDeclaradosBmfResult", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
    @RequestWrapper(localName = "ConsultaDeclaradosBmf", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosBmf")
    @ResponseWrapper(localName = "ConsultaDeclaradosBmfResponse", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService", className = "br.com.bovespa.sinacor_informacaoapoio_integration_service_owner_public_contracts_efinanceira.ConsultaDeclaradosBmfResponse")
    public ArrayOfstring consultaDeclaradosBmf(
        @WebParam(name = "companyId", targetNamespace = "http://www.bovespa.com.br/Sinacor.InformacaoApoio.Integration.Service.Owner.Public.Contracts.EFinanceira.IntegrationService")
        Integer companyId)
        throws IEFinanceiraConsultaDeclaradosBmfAccessIsDeniedFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBmfBusinessFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBmfGeneralFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBmfInvalidSessionFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBmfLicensingFaultFaultFaultMessage, IEFinanceiraConsultaDeclaradosBmfValidationFaultFaultFaultMessage
    ;

}
